### ISSUE TITLE
Japhug tɤ-pɤtso "child": child as "descendant" or "young human"?

### ISSUE THREAD

**Issue by LinguList** [digling/sinotibetan#22]
We have only "the child (descendant)" and "the child (young human)" in our concept list, so a decision needs to be made regarding the meaning of the word. If it has the broad meaning, one might either assign it to both concepts, or set up a new concept "the child" (but I would prefer to keep the list to the 250 meanings, and there, we only list "the child (young human)", no other forms.

If anybody knows the solution, please log in via [this link](http://tsv.lingpy.org?remote_dbase=sinotibetan&file=sinotibetan&preview=280&basics=DOCULECT|CONCEPT|IPA|TOKENS|POS|NOTE|COGID|SOURCE&doculects=Japhug&concepts=the child|the child (descendant)|the child (young human)) and mark this issue later as solved.

**Comment by rgyalrong** [comment]
I tried to click on the link, but I get an empty page. 
tɤ-pɤtso is "the child (young human)"
tɤ-rɟit is "the child (descendant)"

**Comment by LinguList** [comment]
works for me now, it may be due to slow internet, I suggest to retry by
refreshing the page a couple of times.

**Comment by LinguList** [comment]
I just changed the entry, as it was the otehr way round in the current
database.
