### ISSUE TITLE
the hair in Japhug: body hair or head hair

### ISSUE THREAD

**Issue by LinguList** [digling/sinotibetan#23]
we have two glosses in the db:

* the body hair (body hair or fur)

and

* the hair (of the head)

Japhug has the gloss "the hair" without specification, as you can access via [this link](http://tsv.lingpy.org?remote_dbase=sinotibetan&file=sinotibetan&preview=280&basics=DOCULECT|CONCEPT|IPA|TOKENS|POS|NOTE|COGID|SOURCE&doculects=Japhug&concepts=the body hair (hair or fur)|the hair|the hair (of the head)). It is important to resolve this case, since otherwise, the word cannot be accessed.

**Comment by rgyalrong** [comment]
tɤ-rme is "the body hair (body hair or fur)"
tɤ-kɤrme is "the hair (of the head)"

**Comment by LinguList** [comment]
super, I saw it is solved, closing this now
