### ISSUE TITLE
Kuki-Chin

### ISSUE THREAD

**Issue by rgyalrong** [digling/sinotibetan#26]
We need a Kuki-Chin language in the database. Check the coverage for 
Hakha Lai:
http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/gnis?lexicon.lgid=1947
Falam:
http://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/gnis?lexicon.lgid=1923

**Comment by LinguList** [comment]
would vanbik also qualify?

**Comment by rgyalrong** [comment]
These references are from VanBik; I think we should use languages, not reconstructions

**Comment by LinguList** [comment]
agreed, I was more thinking of the languages IN vanbik, but if they are
separate, I prefer that, as we should always try to get the original
sources.

**Comment by LinguList** [comment]
Problem with Hakha and Falam:

* coverage falam: < 130
* coverage Hakha: 153 

Coverage is far too low. This is automatic coverage, but I inspected Hakha, and we explicitly miss words such as "woman", "sand", "thin", etc., so I don't think this will give us much more...

**Comment by LinguList** [comment]
More hopeful might be this source:

* https://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/source/GEM-CNL

With Central Chin Lushai [Mizo].

Automatic mapping gives: 198 / 250 = 0.79%. Mapping is not 100% okay, so should be checked and enhanced, I assume we might get as many as 220 concepts, if we're lucky. But the word for "two" is missing...

**Comment by LinguList** [comment]
Update: the other potential soruce by here is worse (148 concepts automatically covered, many wrong hits):

*  https://stedt.berkeley.edu/~stedt-cgi/rootcanal.pl/source/PB-CLDB
