### ISSUE TITLE
Rgyalrong

### ISSUE THREAD

**Issue by rgyalrong** [digling/sinotibetan#27]
Je rajoute le situ (rGyalrong_Maerkang), 257 entrées

**Comment by LinguList** [comment]
cool! Il me faut changer le website pour que l'on pourra choisir cette langue avec les autres. Je vais le faire demain le matin.

**Comment by rgyalrong** [comment]
fini!

**Comment by rgyalrong** [comment]
commence: +yidu, +qiang, +motuomenba

**Comment by LinguList** [comment]
est-ce que tu peut me donner des details bibliographique sur les sources? J'en aurai besoin pour la documentation en github.

**Comment by rgyalrong** [comment]
ce sont les donnés qui existent déjà, que je commence à cognatiser

**Comment by LinguList** [comment]
ah, alles klar!

**Comment by LinguList** [comment]
Ok, c'est fini. Le [lien](http://dighl.github.io/sinotibetan/) contient les 20 langues maintenant.
