### ISSUE TITLE
Combining multiple entries

### ISSUE THREAD

**Issue by rgyalrong** [digling/sinotibetan#28]
At the present moment, when one selects several word forms with unassigned cognate set, and want to combine them with an existing cognate set, only one of the forms is combined, and one has to repeat the "combine" operation as many times as there are words, which, given the slow speed of the connection, considerably slows the workflow.

**Comment by LinguList** [comment]
very bad thing, didn't notice that before, but I see why it happens. As
a first workaround, I'd suggest to assign all new forms to one new
cognate set (using the NEW feature) and then to combine the two groups.

Alternatively, what will be also much faster (but it may introduce
errors), you could directly work in the wordlist panel: if you either
pre-select only one concept, you also see the column COGID, and can edit
it directly. AND you can leave teh "cognates panel" open to quickly
switch to the next concept, as the cognates panel synchronizes with the
wordlist. Given that we have only 20 languages, and cognates are already
assigned by now, this may be the fastest solution. One more trick: if
you want to have a new ID (cognate identifier), just type in a "?" in
the COGID cell of your choice, and the new id (maximizing existing ones)
will be calculated.

I'll aslo check with the server, as there is a flag that allows for
asynchronous working, which might be switched off and also slowing
things considerably down...

**Comment by LinguList** [comment]
just check the async flag: it is missing, so operations always feed back
to server and wait for answer.

You can turn the asyncronous work on by adjusting your URL:

Start from this part:

http://tsv.lingpy.org/?remote_dbase=sinotibetan&

and add the following:

http://tsv.lingpy.org/?remote_dbase=sinotibetan&async=true&

I'll later adjust it in the official link on the website.

But be careful and check once in a while using the history-link I sent
you to see whether things were actually stored...

**Comment by rgyalrong** [comment]
It is much quicker this way, thank you! BTW, when you modifiy the link, please add "borrowing" among the  columns that are automatically included, we always need this one.

**Comment by LinguList** [comment]
will do. I'll leave this issue open until this is done. It is also
essential to include borrowing in the backup, as the backup is done on
our "base link", so the link that is online.

**Comment by LinguList** [comment]
just checked: borrowing is already there as a default. Yet it is hidden. Would you prefer to have the column already visible when loading the data?

**Comment by LinguList** [comment]
okay, borrowing is now also added automatically, that is, when loading the link, it will appear immediately as open column.
