### ISSUE TITLE
New languages

### ISSUE THREAD

**Issue by rgyalrong** [digling/sinotibetan#29]
After having finished Motuo+Yidu+Qiang
I suggest adding, among the languages on the list with large coverage:

Xumi
Lyuzu
Zhaba

**Comment by rgyalrong** [comment]
I have already started working on Xumi, Lyuzu and Zhaba

**Comment by LinguList** [comment]
okay, will soon upload the modified link to [http://dighl.github.io/sinotibetan](http://dighl.github.io/sinotibetan).

**Comment by LinguList** [comment]
done
