### ISSUE TITLE
Concepts to remove

### ISSUE THREAD

**Issue by rgyalrong** [digling/sinotibetan#36]
Also "father" and "mother": too many nursery forms, difficulty to tell inherited words from real cognates.

**Comment by LinguList** [comment]
Allright, that makes 223 working concepts then. I'll try and reduce to 220, as I prefer nice numbers. Then we still have enough for the comparison between 220 and 200 list, and we could even go smaller.

**Comment by LinguList** [comment]
okay, here's a current list (adding two suggestions of myself):

* father
* mother
* above
* below, under

Father and mother rank rather high, above and under are bad concepts, as they are dificult to cognatize. If we head for 200 concepts in the end, we need to trade two of the less high-ranked concepts (200-220), but this seems to be okay, we could take, e.g., "earthworm" and "know" (know is at least a Swadesh concept). But let's not haste. We're now linking the new data to have our 220 concepts, and later decide finally which ones to kick out.

**Comment by rgyalrong** [comment]
father and mother should definitely be removed, as so many languages have nursery words.

**Comment by LinguList** [comment]
I just also saw we have "feather" "head hair" and "body hair", maybe keep only one?

**Comment by rgyalrong** [comment]
feather and body hair maybe can be kept.

**Comment by LinguList** [comment]
I'll make a colexification analysis afterwards, if all data is assembled. From that we can easily see where most of the dependencies are...

**Comment by rgyalrong** [comment]
Maybe we can have an objective measure of the colexification rate, and then write in the paper that concept with X% overlap have been removed.

**Comment by rgyalrong** [comment]
The entry "man (male human)" as opposed to "man" is problematic also.

**Comment by rgyalrong** [comment]
Some concepts are attested in too few languages to be useful, such as:
arm
back 
banana

**Comment by rgyalrong** [comment]
For other concepts, we only have compounds, which I am not sure how to handle:

afternoon
all

**Comment by LinguList** [comment]
Okay, I suppose we do the following: we run our analysis for cross-semantic cognate detection and return the results. Usually, this will merge some concepts, but not all. With these, you can then evaluate and we can pick the best concept. E.g., if one has 2 and 10 as concept, 20 is often not needed, and "tear" is "eye water" in most of the languages there.
