### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by rgyalrong** [digling/sinotibetan#37]
In the block "Edit and align cognate sets", add the number of concepts, and the place at which the user presently is (form instance 22/200 would indicate that thzere are 200 concepts, and that the user is working on the 22nd one).

**Comment by rgyalrong** [comment]
In addition, when a user goes through the whole list of concepts, and has to stop in the middle, it could be good to have a way to memorize it on the interface, rather than having to write it down somewhere

**Comment by LinguList** [comment]
just figured that it might be easy to fix, at least for concept numbers, as they are always there, even if not shown, and will try to do so on Monday.

**Comment by LinguList** [comment]
Fixed now. It indicates in cognates-panel the number of concepts left and which you are currently working on.
