### ISSUE TITLE
Chinese dialects

### ISSUE THREAD

**Issue by LinguList** [digling/sinotibetan#39]
@laiyunfan will add this manually. We will decide next week on how to add it (directly via the EDICTOR or via some text-file as template).

**Comment by LinguList** [comment]
@laiyunfan, I just renamed this issue, and I'd propose that you add a bullet list here, illustrating the status of the language varieties you decided to add.

**Comment by laiyunfan** [comment]
Ok. Here are the varieties that I decided to add/refine:
- [x] Cantonese
- [x] Hakka (Longgang, Shenzhen)
- [x] Hakka (Xingning)
- [ ] Chaozhou (Chaozhou)
- [ ] Chaozhou (Jieyang)
- [ ] Beijing Mandarin

The two Chaozhou dialects will be done within one or two days.
More varieties are possible, but have to do it gradually.

**Comment by LinguList** [comment]
So currently, we have 39, plus six Chinese varieties, plus Tangut, plus Mikir, plus Ukhrul, and Hayu. Makes 49, so we can add Kanauri or the second Khroskyabs variety, even if it's less interesting, and we'll have the 50. This looks good. @laurentsagart, and @rgyalrong, if you have additional suggestions for the last language (maybe compare with the spreadsheet, some languages are difficult, like, e.g., Newar, with low coverage), let me know, and we'll see what we can do.

**Comment by nh36** [comment]
Folks. An innocent question. There are several major dictionaries available
for Newar with at least one in digital format. How can there possibly be
low coverage?

For example--
https://zenodo.org/record/815581#.WbFw3ooo9z0

**Comment by LinguList** [comment]
Before adding the Chinese dialects, we'll cognatize them, first doing the partial cognates, later automatizing creation of full cognates. I'll arrange it in such a way that the OC data by @laurentsagart is taken as a reference, so we show for the words, which is the OC cognate ID. Then, when cognatizing for the big database, we'll need some quick search for cognates between dialects which might go *beyond* the OC sample. I don't really know, but I remember @laurentsagart was mentioning that there were a few of those cases potentially.

**Comment by laurentsagart** [comment]
There is a cognate set for 'egg' which does not have a Chinese character, and consequently no OC reconstruction, because it is vulgar (also used as 'testicle') and doe snot appear in texts, but it had to be in OC because it has sound correspondences with a set of TB forms for 'egg'.
