### ISSUE TITLE
Mikir (unclassified)

### ISSUE THREAD

**Issue by LinguList** [digling/sinotibetan#41]
Following @laurentsagart's suggestion, I just ordered this book via library (hope they can get it), I sent them the Amazon link:

* https://www.amazon.com/Dictionary-Mikir-Language-Mikir-English-English-Mikir/dp/B002NEOV2Y

Once having the book (it's a reprint from an older version, but this old version is hard to get), we'll see how well we can link it. If it's worth, me and @laiyunfan will share work in typing the 200 entries off. But we'll first of all have a closer look whether we get the coverage we need to avoid unnecessary work.

**Comment by LinguList** [comment]
Alternative is [Neighbor from 1878](https://archive.org/details/vocabularyinengl00neigrich). It is online at archive.org (thanks, @nh36, for mentioning this to me).

**Comment by LinguList** [comment]
Yet another source is [this one](https://books.google.de/books/about/Karbi_Grammar.html?id=TmwtAAAAMAAJ&redir_esc=y) of the Kabir variety.

**Comment by LinguList** [comment]
We have a scan for that (thanks again, @nh36 for pointing it out).

**Comment by d97hah** [comment]
Have you checked with Linda Konnerth whether she can supply a lexicon?

2017-08-10 11:09 GMT+02:00 Johann-Mattis List <notifications@github.com>:

**Comment by LinguList** [comment]
A, sorry, saw your post, @d97hah only now, somehow, github does not send emails any more to me. We follow this up in #45 now, and our current plan is to stick to the source which we have now, but I'd propose that @laiyunfan also contacts Linda Konnerth to ask her: if she has a lexicon, it would even be better, if not, we'll need to include the language variety in the book anyway.

**Comment by LinguList** [comment]
Redirecting this thread to #45, so closing it now.
